version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./macdash
    ports:
      - "3000:80"        
    depends_on:
      - backend
    restart: always
